### ISSUE TITLE
What if an author gets the previous-version wrong in their published package ?

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#105]
Author publishes versions 1.0.0 -> 1.1.0 -> 1.2.0 -> 1.3.0 -> 1.4.0
Then discovers that the previous-version leaf in 1.4.0 accidently still says 1.2.0 (instead of 1.3.0).
Even worse - they discover that 1.2.0 accidently had previous-version as 1.0.0. (can't just reissue 1.2.1 because then 1.3.0 is still using a "bad parent".
Should we give some guidance for dealing with this in the packages draft ?

**Comment by rgwilton** [comment]
Also considering removing nbc-changes flag from a package definition:
  - It should be possible to determine this by doing a mechanical comparison between two package versions.
  - We should check that we can always determine this.

Another choice could be to make the leaf optional?

Jason to update.

**Comment by jsterne** [comment]
- remove the parent leaf ?  YES - remove it:
   - have ancestry stored somewhere else outside the module ? out of scope
   - ancestry isn't needed. Can have mistakes that are not really correctable.

**Comment by rgwilton** [comment]
Next step: proposal for text changes in the draft.

**Comment by jsterne** [comment]
Need proposal for text changes in the draft (to remove any references to previous-version, ancestry, etc.

**Comment by jsterne** [comment]
We decided to also remove the nbc-changes flag as part of this issue:
NBC marker and history in a package:
- don't *need* the nbc-changes and it could be incorrect or in conflict with actual state. Can be deterministically determined analyzing the package & modules

**Comment by jsterne** [comment]
This was closed with PR#129
