### ISSUE TITLE
Track instance-data format for example

### ISSUE THREAD

**Issue by xorrkaz** [netmod-wg/yang-ver-dt#108]
Section 3.4.2 of yang-semver has an instance-data example that needs to be tracked so any changes there can be properly reflected.

**Comment by xorrkaz** [comment]
This has moved to Section 3.5.2.  @BalazsLengyel, please consider watching this to make sure instance data is still accurate.

**Comment by BalazsLengyel** [comment]
File with correct tabulation posted in email.

**Comment by xorrkaz** [comment]
I have committed this work to master.
