### ISSUE TITLE
Add guidance text about warning NBC changes might break imports

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#11]
This should be added into an appropriate place in chapter 8:

    <t>TODO - Perhaps guidance text should also warn about making nbc
    changes that could break imports.  E.g. this could be an example of
    where making something obsolete might be better than removing
    it.</t>

**Comment by Reshad-Rahman** [comment]
Reshad to look at current text and determine if something specific needs to be added or already covered.

**Comment by Reshad-Rahman** [comment]
This was discussed at IETF108 and the question came up (from Kent) why the "revision-or-derived" extension isn't BC. This was then discussed on the [alias](https://mailarchive.ietf.org/arch/msg/netmod/dGQX4jeQWjPT1TqPjk8_yjVJhFM/). As of now most authors seem to prefer the open-ended flavour. Reshad (and maybe Balazs) think the -bc extension would be useful too. We haven't closed on whether we have 1 extension only or the -bc one too. Parking this for now.

**Comment by jsterne** [comment]
A separate issue was created to discussed the need for revision-or-derived-compatible.

This issue should keep the original intent in the title (and is still valid) -> should we have guidance about NBC changes and how they can break imports?  The guidance text probably depends on the decision around Issue #75

**Comment by Reshad-Rahman** [comment]
Issue #75 has been closed as per discussions on Dec 14th 2020 virtual interim. Issue #76 has been opened to see how compatibility constraints can be specified as meta-data.

**Comment by Reshad-Rahman** [comment]
Text was added to latest rev, need to be discussed with WG

**Comment by rgwilton** [comment]
In Reshad's dev branch, but not pushed.

Issue can be closed once latest branch has been pushed.
