### ISSUE TITLE
YANG semver examples in 3.2.2 and 3.4.1

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#114]
Hi Reshad, all,

 

Good catch.

 

I think that it would be better if the two align.  Could we tweak the example to help align it, but still keep some examples of branching?  E.g., changing the diagram to something like below.

 

This diagram is meant to illustrate the relationship between the revisions.  I.e., you should be able to walk from any leaf revisions back to the root and that should reflect the version history.

 

           0.1.0

             |

           0.2.0

             |

           1.0.0

             | 

           1.1.0 -> 1.1.1_compatible -> 1.1.2_non_compatible

             |  

           1.2.0 -> 1.2.1_non_compatible -> 1.2.2_non_compatible

             |   \ 

           2.0.0  \

             |     1.3.0 –> 1.3.1_non_compatible

           3.0.0     |

             |     1.4.0

           3.1.0

 

The text below the diagram, e.g.,

 

      0.1.0 - first pre-release module version

 

      0.2.0 - second pre-release module version (with NBC changes)

 

      1.0.0 - first release (may have NBC changes from 0.2.0)

 

              . . .

 

… represents the chronological order that those revisions were created.  E.g., illustrating that 1.1.1_compatible is created after 1.2.0 has been related (or otherwise It possibly would have been released as 1.2.0 instead)

 

The example in 3.4.1 should show one of the revision histories, i.e., the mainline one.  Probably it would be helpful if it explicitly stated this so that readers know that they can compare them.

Regards,

Rob

 

 

From: Sterne, Jason (Nokia - CA/Ottawa) <jason.sterne@nokia.com> 
Sent: 28 October 2021 20:58
To: Reshad Rahman <reshad@yahoo.com>; Rob Wilton (rwilton) <rwilton@cisco.com>; Balázs Lengyel <balazs.lengyel@ericsson.com>; Joe Clarke (jclarke) <jclarke@cisco.com>
Subject: RE: Question on semver example

 

OK - I see what you mean about baz.

 

But it effectively makes the tree look like this then.

 

 

           0.1.0

             |

           0.2.0

             |

           1.0.0

             | 

           1.1.0 -> 1.1.1_compatible -> 1.1.2_non_compatible

             |  

           1.2.0 -> 1.2.1_non_compatible -> 1.2.2_non_compatible

             | 

           1.3.0

             |

           1.3.1

             |

           2.0.0

             |

           3.0.0

                \

                 3.1.0

 

 

I liked the original tree showing a fairly major branching point.

 

From: Reshad Rahman <reshad@yahoo.com> 
Sent: Thursday, October 28, 2021 3:45 PM
To: Rob Wilton (rwilton) <rwilton@cisco.com>; Balázs Lengyel <balazs.lengyel@ericsson.com>; Joe Clarke (jclarke) <jclarke@cisco.com>; Sterne, Jason (Nokia - CA/Ottawa) <jason.sterne@nokia.com>
Subject: Re: Question on semver example

 

Chronology is not in the diagram, but the list after mentions it. 2.0.0 can not be from 1.0.0, because 3.0.0 wouldn't have "baz". And my interpretation is that 2.0.0 is off 1.3.1.

 

   Assume the tree diagram above illustrates how an example YANG
   module's version history might evolve.  For example, the tree might
   represent the following changes, listed in chronological order of
   when the revisions were published, from oldest revision to newest:
 

      1.0.0 - first release (may have NBC changes from 0.2.0)
  
      1.1.0 - added new functionality, leaf "foo" (BC)
  
      1.2.0 - added new functionality, leaf "baz" (BC)
  
      1.3.0 - improve existing functionality, added leaf "foo-64" (BC)
  
      1.3.1 - improve description wording for "foo-64" (Editorial)
  
      1.1.1_compatible - backport "foo-64" leaf to 1.1.x to avoid
      implementing "baz" from 1.2.0 (BC)
  
      2.0.0 - change existing model for performance reasons, e.g. re-key
      list (NBC)
  
      1.1.2_non_compatible - NBC point bug fix, not required in 2.0.0
      due to model changes (NBC)
  
      3.0.0 - NBC bugfix, rename "baz" to "bar"; also add new BC leaf
      "wibble"; (NBC)
 

On Thursday, October 28, 2021, 03:33:52 PM EDT, Sterne, Jason (Nokia - CA/Ottawa) <jason.sterne@nokia.com> wrote:

 

 

I don't think chronology is included in that diagram. We could add chronology as the X axis but then we'd have to indent later versions more, etc.

 

From: Sterne, Jason (Nokia - CA/Ottawa) 
Sent: Thursday, October 28, 2021 3:32 PM
To: 'Reshad Rahman' <reshad@yahoo.com>; Rob Wilton (rwilton) <rwilton@cisco.com>; Balázs Lengyel <balazs.lengyel@ericsson.com>; Joe Clarke (jclarke) <jclarke@cisco.com>
Subject: RE: Question on semver example

 

The tree is a parent/child relationship tree between versions.

 

From: Reshad Rahman <reshad@yahoo.com> 
Sent: Thursday, October 28, 2021 3:30 PM
To: Sterne, Jason (Nokia - CA/Ottawa) <jason.sterne@nokia.com>; Rob Wilton (rwilton) <rwilton@cisco.com>; Balázs Lengyel <balazs.lengyel@ericsson.com>; Joe Clarke (jclarke) <jclarke@cisco.com>
Subject: Re: Question on semver example

 

And I think the 3.4.1 example is correct according to chronological list in 3.2.2. 

 

The tree seems to be wrong (again according to chronological list), or I misunderstood its intent.

 

On Thursday, October 28, 2021, 03:25:32 PM EDT, Joe Clarke (jclarke) <jclarke@cisco.com> wrote:

 

 

If we did that, the example in 3.4.1 wouldn't be very interesting.

Joe

On 10/28/21 15:24, Sterne, Jason (Nokia - CA/Ottawa) wrote:

I don't think so. I think it is showing YANG semver.

 

I like the tree as-is. I think we should fix 3.4.1 (to maybe follow a different branch if necessary to illustrate the point).

 

From: Reshad Rahman <reshad@yahoo.com> 
Sent: Thursday, October 28, 2021 3:17 PM
To: Rob Wilton (rwilton) <rwilton@cisco.com>; Balázs Lengyel <balazs.lengyel@ericsson.com>; Sterne, Jason (Nokia - CA/Ottawa) <jason.sterne@nokia.com>; Joe Clarke (jclarke) <jclarke@cisco.com>
Subject: Re: Question on semver example

 

So looking at this again, I *think* that the tree is attempting to show the software releases, not the "hierarchy" of module versions.

The chronological list in 3.2.2 indicates/implies that 2.0.0 is off 1.3.1.

 

On Thursday, October 28, 2021, 03:14:42 PM EDT, Joe Clarke (jclarke) <jclarke@cisco.com> wrote:

 

 

The text doesn't explicitly say that the example module is a realization of the tree above it, but the descriptions and versions make it seem like it is (and should be).

It might be better to show 2.0.0 branch off from 1.3.1 in the tree.  I'll see if I can fix this visually, but we'll see.

Joe

On 10/28/21 15:07, Reshad Rahman wrote:

Hi,

 

The example in https://datatracker.ietf.org/doc/html/draft-ietf-netmod-yang-semver-04#section-3.2.2 shows 2.0.0 as a child of 1.0.0 but the revision history further below (3.4.1) shows 2.0.0 as a child of 1.3.1. I assumed that 3.4.1 would match what's in 3.2.2, is that not the case? Or am I misreading 3.2.2?

 

Thanks,

Reshad.

**Comment by Reshad-Rahman** [comment]
Nov 2 meeting: we'll go with 1.2.2_non_compatible branch for example module revision history in 3.4.1.

**Comment by jsterne** [comment]
Examples updated and present in latest version
