### ISSUE TITLE
Need to define editorial, bc, nbc impact of adding, changing, removing extension stmts

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#12]
Need to classify both the default behavior, and also state that the extension should define how it is impacted.

This could be a hassle for tooling.

**Comment by BalazsLengyel** [comment]
Just refer to https://github.com/netmod-wg/yang-next/issues/54
    Balazs
    
    On 2019. 03. 08. 15:47, Robert Wilton
      wrote:
    
    
      
      Need to classify both the default behavior, and also state that
        the extension should define how it is impacted.
      This could be a hassle for tooling.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/netmod-wg/yang-ver-dt","title":"netmod-wg/yang-ver-dt","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/netmod-wg/yang-ver-dt"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Need to define editorial, bc, nbc impact of adding, changing, removing extension stmts (#12)"}],"action":{"name":"View Issue","url":"https://github.com/netmod-wg/yang-ver-dt/issues/12"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/netmod-wg/yang-ver-dt/issues/12",
"url": "https://github.com/netmod-wg/yang-ver-dt/issues/12",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Balazs Lengyel                       Ericsson Hungary Ltd.
Senior Specialist
Mobile: +36-70-330-7909              email: Balazs.Lengyel@ericsson.com

**Comment by Reshad-Rahman** [comment]
Case by case, extension writers should define behaviour.

**Comment by jsterne** [comment]
We need to bring this one to the larger NETMOD WG

**Comment by rgwilton** [comment]
Rules for definition extension statements, 7950: Adding extension is BC, changing/removing is NBC.

What about use of extension statements:
 - SHOULD specify the behaviour in the extension definition (as per Reshad's slides)
 - Otherwise, without knowledge, then the behaviour is indeterminate (may break compatibility).

Balazs to propose text.

**Comment by rgwilton** [comment]
Waiting for Balazs to propose text.

**Comment by rgwilton** [comment]
Proposed text, that was agreed on 18 March meeting (Jason absent):

“Adding, removing, or changing a statement that was defined using the YANG “extension” statement (usage of an extension) may or may not result in an NBC change. Hence, the definition of the extension SHOULD state whether such changes are backwards compatible.”
