### ISSUE TITLE
Does the solution require a new version of YANG

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#14]
Does the solution require a new version of YANG?

Probably some of it can be done here, and perhaps other parts might be best handled as part of the next revision of YANG.

This issue is also tracked in the main body of the document.

**Comment by BalazsLengyel** [comment]
IMHO the only change that contradicts rfc7950 is that we do allow NBC changes. However as NBC changes are already made today (in possible violation of the RFC), and as rfc7950 does itself allows some NBC changes via the status statement, IMHO there is no need for a new YANG version.

**Comment by sunseawq** [comment]
My impression, if YANG 1.2 or YANG 2.0 accept NBC changes without adding new definition with new identifier, everything will be moved smoothly.

**Comment by Reshad-Rahman** [comment]
Do we have consensus now that we don't need a new version of YANG?

**Comment by Reshad-Rahman** [comment]
For the moment the assumption is that the solution does not require a new YANG version
