### ISSUE TITLE
Clarify algorithm for determining ancestry of module revisions

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#147]
Module Versioning draft: Check if we are clear enough on a description of how to determine if a module revision Y is a descendant of another module revision X (i.e. search up the history of module revision Y and see if revision X is listed).
- what to do in an environment where authors strip history out of a module ?  suggest checking the contents of all revisions available in the chain (i.e. go look in N different revisions to fill in the gaps ?) ?  or just say it breaks import by revision ?

**Comment by jsterne** [comment]
This is related to Jurgen's WGLC comment about section 3.5:

* 3.5. Examples for updating the YANG module revision history

  Assuming the 2.x line is backwards compatible but the 3.x line is
  not. How do I figure this out from the linear revision history
  sorted by dates? Is the idea that I always only have a single branch
  in the revision history in a module? Or can there be multiple
  branches documented? Can branches merge again? If I can include the
  history of multiple branches, is the idea that tools have to
  understand the semantics of the revision labels to reconstruct the
  revision history graph in order to make sense of the
  rev:non-backwards-compatible markers?  The linear order could easily
  lead to misinterpretations, revision 2019-04-01 is BC but it would
  appear in chronological order after 2019-03-01, to which it is NBC.

**Comment by jsterne** [comment]
We won't try to explain how to determine if any two revisions are BC vs NBC with each other. 

But we should make sure it is clear how to determine if revision X is derived from revision Y (simply search in the history).

No need to add any further details about the impacts of removing history (already in there).

TBD - Change the word "breakage" when history is removed ?

**Comment by rgwilton** [comment]
Given that we are proposing softening the import by min-revision, I think that this text is less critical, and I propose that we don't attempt to further refine it unless this comes in last call again.

**Comment by rgwilton** [comment]
See https://github.com/netmod-wg/yang-ver-dt/pull/190

I'm proposing adding the following text to resolve this:

OLD:
   A corollary to the above is that the relationship between two module
   or submodule revisions cannot be determined by comparing the module
   or submodule revision date alone, and the revision history, or

NEW:
   For a given YANG module revision, revision B is defined as being
   derived from revision A, if revision A is listed in the revision
   history for revision B.  Although this document allows for a branched
   revision history, a given YANG module revision history does not
   contain all revisions in all possible branches, it only lists those
   from which is was derived, i.e., the module revision's history
   describes a single path of derived revisions back to the root of the
   module's revision history.

   A corollary to the text above is that the relationship between two
   module or submodule revisions cannot be determined by comparing the
   module or submodule revision date alone, and the revision history, or

**Comment by rgwilton** [comment]
+ some other minor cleanup related to import

**Comment by rgwilton** [comment]
Merged wit #190.
