### ISSUE TITLE
File name rules and recommendations

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#148]
Section 3.4.1. File Names (module versioning v-05) describes some YANG module filename options. 

On the weekly call 2022-03-29 we started to question:
1) if we should just give the options with no particular SHOULD or MUST
2) if we really should have any new filename convention at all

Some rough notes from the discussion:
- note: today module names don't *have to* match the filenames (warning in pyang)
- there are actually 3 formats (one without the suffix). Do we just allow all 3 to be valid ?
- in IETF you MUST use xxx ?  <- no. we don't want to mandate this for now.
- should we state that the definitive revision date or revision label is inside the module file (not in the filename, in case of conflict), and the version in the suffix MUST match ? 
- we can't recommend # format today with YANG 1.1.  Maybe for YANG NEXT
- should we even consider dropping the # suffix altogether ?
- our revision-label inside the module is *additive*, but using the # suffix instead of the @ suffix isn't additive and could break current tools
- note that we show an example of YANG Semver here, but there could be N different revision label schemes out there. So tools would often have to ignore what comes after the # anyways...

RFC7950 says:
   module-or-submodule-name ['@' revision-date].yang
   ...
   the optional "revision-date" is the latest revision of the module
   or submodule, as defined by the "revision" statement

RFC8407 says:
   The name string
   form that includes the revision date SHOULD be used.  The revision
   date MUST match the date used in the most recent revision of the
   module.

Also - some of the description in section 3.4.1 may contradict itself, e.g. the mix of SHOULD and MAY here (along with the mix of 'Typically' and SHOULD):
   Typically, only one file name
   SHOULD exist for the same module (or submodule) revision.  Two file
   names, one with the revision date and another with the revision
   label, MAY exist for the same module (or submodule) revision, e.g.,
   when migrating from one scheme to the other.

**Comment by Reshad-Rahman** [comment]
> Have the following approach been discussed, using a prefix for revision label with the current @-notation, example:
> 
> ```
> module-or-submodule ['@' 'label:' revision-label].yang
> ```
> 
> or even just using `l:` as prefix, i.e. `l:revision-label`.
> 
> Instead of using the number sign (`#`).

I think we discussed something along the lines. Tools which expect date to follow @ will break. If I am misremembering, someone please keep me honest...
