### ISSUE TITLE
Does BC or NBC depend on whether the node is config true/false?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#15]
Should the YANG rules on what constitutes a BC or NBC change depend on whether the node is config or state?

In particular, should the change for unit32 to uint64 be a NBC change?

What if the types are the same but the range of values increases (e.g. from 1-100 to 1-1000)?  Clients are obliged to be somewhat graceful in what they receive anyway ...

**Comment by BalazsLengyel** [comment]
The current rules of BC/NBC are not complete. A full rule-set is very long and complicated (we have multiple rules for each YANG statement ending up with 200 little rules).
Just some examples not covered by the rfc7950 definition:

1) Chahging mandatory: 
making  an optional config=true node mandatory is NBC
making an optional config=false node mandatory is BC

2) Decreasing the value range 
removing an enum statement for a config=true node is NBC
removing an enum statement for a config=false node is BC

Similarly statements under an input/output statements differ in BC/NBC requirements.

**Comment by rgwilton** [comment]
Discussed, but no clear solution, left open.

**Comment by sunseawq** [comment]
In our implementation, BC or NBC doesn't depend on whether the node is config true/false.

**Comment by Reshad-Rahman** [comment]
For config false, shrinking the value range should be BC?
Discuss on WG alias.

**Comment by jsterne** [comment]
There are really two issues here:

A) Does BC or NBC depend on whether the node is config true/false?

B) For a config false node, what is the definition/meaning of BC vs NBC?

**Comment by Reshad-Rahman** [comment]
Text in latest rev should be discussed on WG alias

**Comment by jsterne** [comment]
Sent to NETMOD on April 20, 2021:

After some feedback on the WG mailing list and further discussions on the weekly versioning calls, we are proposing that any clarification (above what 7950 describes) of how changes to "config false" nodes may or may not differ from "config true" nodes is out of scope for our versioning work.  We won't specifically call out and address state (config false). 

Any discussions of state vs config for module changes would occur in the context of RFC 7950 (and possibly clarifying what the 7950 text means if/as needed), and in the context of "YANG NEXT".

We'll remove the recently added section about state (config false) from the next module versioning draft.
