### ISSUE TITLE
Add annotation for describing a change as nbc

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#150]
draft-ietf-netmod-yang-schema-comparison-01 has annotations to indicate editorial and bc changes, but no annotation for an nbc change.  

The original thinking here was that nbc would be the default behaviour (e.g., for a description change), and hence a separate annotation to indicate nbc isn't required.  But if the annotation description is useful to indicate why (or how) such a change is being made then allowing an annotation for an nbc-change may be helpful.

There is also an open question as to which drafts these tags should be specified in, e.g., the tooling draft or the module versioning draft.

**Comment by jsterne** [comment]
Added to PR#157
