### ISSUE TITLE
Is changing stmt ordering BC

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#153]
We prevent it when it is used within input and output statements, but what about groupings?  Do we ban changing the ordering in groupings as well, or ban changing the ordering at all?

**Comment by jsterne** [comment]
Updated text added to PR#157

**Comment by jsterne** [comment]
Jason to do: check that my previous comment is correct (or was it another issue).
Decision from Oct 4 meeting: reordering will be NBC as per 7950 and we won't change that in our work.

**Comment by jsterne** [comment]
Removed the bullet in 3.1.1 that allowed re-ordering of statements (outside input & output). Updated in PR#157.
