### ISSUE TITLE
Do we need to allow annotations to flag NBC changes as BC?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#154]
E.g., device would have rejected config anyway, but pattern or range has been reduced so that the YANG more accurately reflects the implementation

**Comment by BalazsLengyel** [comment]
Yes. 
1) Tool might not be able to decide if a change is BC/NBC. Often the default will be NBC. However the designer might know that the change is actually BC, e.g. restructuring a regexp.
2) If the regexp was incorrect (e.g. if a regexp for IP-Address allowed 355.355.355.355 and it was corrected) that formally is decreasing  the valuespace, however the "real" valuespace is not changed. The tool would label this as NBC, but the designer knows it is BC or maybe editorial.
3) leaf a { type { int32 { range 0..255; }}} is changed to leaf a {type uint8; } 
The tool might not be able to understand that this is a BC change, labeling it NBC. 
4) A vendor module lives in a walled garden where ALL clients are known. In this case a change that is really NBC might not be a problem for the clients: the change is BC for all users.

**Comment by jsterne** [comment]
Added to PR#157
