### ISSUE TITLE
May need to update data/revision on per node annotations when copied

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#155]
If copying changes between different branches where the changes already have per node annotations, then it will probably be necessary to check/update the annotations with a new revision-date/label (because otherwise they might reference to a revision/version that isn't in the branches modules history).

Further, the annotations might not apply depending on what the history is like in that new branch.  E.g., an nbc-change that is copied might not still be a nbc-change in the branch.

**Comment by jsterne** [comment]
IMO there shouldn't really be such a thing as "copying changes between different branches". At least not a simply copy-n-paste.  If branch 1 has a leaf that you want to add to branch 2, then you're just adding a leaf to branch 2. Not copying *any* history or tags IMO.

**Comment by rgwilton** [comment]
I basically agree.  My thinking was more that we might just need to add a short explanation as to what should be done in this case.  I.e., doing a cut and paste, isn't acceptable and hence care is needed when porting changes between disjoin branches.

**Comment by jsterne** [comment]
Added to PR#157
