### ISSUE TITLE
Soften import revision-or-derived to make it a suggestion rather than a mandate?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#158]
In YANG 1.1, the selection of module version for imports is left fairly undefined.

Does import "revision-or-derived" break this?

Can be argued both ways, but one option could be to change this tag meaning to be a recommendation (for authors and tools) rather than an absolute requirement.

Specifically, change the meaning of revision-or-derived such that:
 - it is just a suggestion rather than a hard requirement.
 - a tool can make use of this to help select an appropriate version but is not required to do so.
 - a tool may choose to warn if it selects an alternative version, which it may have a valid reason to do, e.g., if a type has been backported to a different branch, hence a non-derived type could still be valid.
 - we could potentially strengthen this in a new version of YANG (e.g., if the extension statement gets moved into the YANG language and is required to be supported by all tools supporting the new version).

next step: Ask Juergen if this would alleviate one of his concerns about doing this work in YANG 1.1.

**Comment by jsterne** [comment]
I think we all agreed that if the tool can't find the recommended version (i.e. it isn't in the set available to it, in packages that means not part of the package for instance), then it can use some other version.
But if it *does* have a version matching the "revision or derived" constraint, do we want to say it MUST use it in that case ?

**Comment by rgwilton** [comment]
Also see https://github.com/netmod-wg/yang-ver-dt/pull/183/files

**Comment by rgwilton** [comment]
Fixed in [7684fa7](https://github.com/netmod-wg/yang-ver-dt/commit/7684fa754fb8cfd13b13e4e952cafb3a874a1284)
