### ISSUE TITLE
NBC changes are for vendors, not IETF

### ISSUE THREAD

**Issue by janlindblad** [netmod-wg/yang-ver-dt#161]
On June 14, Andy Bierman wrote on the subject "draft-ietf-netmod-yang-module-versioning-05: NBC Changes":

"""
Given that RFCs take so long to publish, it seems unlikely that
we would ever be in a position to make a "real" NBC change
in the middle of a release train, such that all of the client code
already deployed will break immediately when the upgrade is done.
We can NEVER just remove the old version.
"""

We need to clarify that NBC changes are for vendors, but not IETF.

**Comment by jsterne** [comment]
Draft discourages, but allows NBC, including in standard modules (and that is needed, IETF has already made NBC changes).  No text changes proposed.
(TBD - do we need to reply back to the WG about this particular item ?)

**Comment by BalazsLengyel** [comment]
Email sent 2022-10-17 19:52

**Comment by jsterne** [comment]
After some more discussion, the proposal has been updated to the following change:

Remove Old text:
Where pragmatic, updates to YANG modules SHOULD be backwards-compatible, following the definition in [Section 3.1.1]

After the paragraph that starts with this:
“A new module revision MAY contain NBC changes…
add this paragraph:
Note that NBC changes often create problems for clients, thus it is recommended to avoid making them.”

**Comment by jsterne** [comment]
https://github.com/netmod-wg/yang-ver-dt/commit/0a0ba29563fcb01e5fa69b8989db2cf027574105
