### ISSUE TITLE
Correctly describe moving leafs into choices for BC purposes

### ISSUE THREAD

**Issue by janlindblad** [netmod-wg/yang-ver-dt#162]
On June 2, Italo Busi wrote on the subject "Another comment/question on appendix B.2 of draft-ietf-netmod-yang-module-versioning-05". He proposes a way to deprecate old leafs by adding a choice, and notes that the current 7950 rules do not allow this, and argues that this could be changed.

"""
The original (using the old style mode) is in mw-option@2022-04-01.yang. the new version of mode (rlt-mode) is in mw-option@2022-05-26.yang
 
However, when we use pyang to check backward compatibility we get an error message (see the nbc.out file in github):
 
mw-option@2022-05-26.yang:47: error: the leaf 'mode', defined at mw-option@2022-04-01.yang:40 is illegally removed
mw-option@2022-05-26.yang:50: error: the mandatory node mode-option is illegally added
"""

Scott Mansfield and Jason Sterne replies to this, and on June 7, Jason Sterne writes:

"""
Another reason just occurred to me why moving the old leaf inside a "choice" is NBC: it may not affect the data tree path to that element of instance data, but it does affect the schema path to that element.
 
So if it was a container, for example, and some other module was augmenting that container, the augmentation path would be broken if it was moved inside a choice.  I'm not certain that maintaining compatibility with an augmenting module is a fundamental criteria but it certain is an impact to an ecosystem of modules.
 
Of course all the above is for a fairly "strict" manner of defining backwards compatibility. The actual impacts to a client of moving an old leaf into a new "choice" (where other cases of the choice contain purely new elements that didn't exist before) are often going to be minor to nothing. But the users of the module would need to take a look at it.
 
This discussion is also making me realize that our text in B.2.3.1 may have a mistake. An author can't stick the old leaf into a "choice" and be 100% BC so we should probably remove that option.
 """

Section B.2.3.1 needs to be checked to see if what it suggests indeed is compatible with the BC rules.

**Comment by jsterne** [comment]
Removed the "choice" option, and also removed examples of using version selection (save that for the version selection draft). Updates in PR #174
