### ISSUE TITLE
Clarify requirements on versioning schemes

### ISSUE THREAD

**Issue by janlindblad** [netmod-wg/yang-ver-dt#163]
On March 6 Jürgen Schönwälder wrote on the subject "WG Last Call: draft-ietf-netmod-yang-module-versioning-05"

"""
  Example 2 finally tells me by way of example what derived means.  I
  suggest to define the notion of "derived" earlier. The example seems
  to suggest that derived is along the partial order induced by the
  version labeling scheme (and this means tools need to be able to
  reconstruct the versioning tree (can it be more than a strict
  tree?). If this document is expected to work with different
  versioning schemes, it seems this document needs to spell out which
  requirements a versioning scheme has to satisfy for this document to
  work properly (e.g., that there is a defined partial order on
  version labels).
"""

We need to clarify the text.

**Comment by jsterne** [comment]
is this already in our draft ?  Some statement like: revision b derives from revision a if revision a is in the history of revision b.

**Comment by janlindblad** [comment]
I too prefer text1, but think text2 would be OK.

**Comment by xorrkaz** [comment]
While I like the example in 2, I think 1 is a bit clearer.

**Comment by jsterne** [comment]
Addressed by PR #190

**Comment by rgwilton** [comment]
Merged wit #190.
