### ISSUE TITLE
Revision-date YANG description improvements

### ISSUE THREAD

**Issue by janlindblad** [netmod-wg/yang-ver-dt#166]
On March 6 Jürgen Schönwälder wrote on the subject "WG Last Call: draft-ietf-netmod-yang-module-versioning-05"

"""
8. Module Versioning Extension YANG Modules

  - Replace '\d{4}-\d{2}-\d{2}' with the pattern used in RFC6991bis
    (the \d does some surprising things, so I dropped it everywhere).

  - RFC6991bis introduces the type revision-identifier but given this
    work is getting stable it seems more logical to call the type
    revision-date. This is also the term RFC 7950 uses. And I think
    revision-date should be defined in ietf-yang-revisions and not in
    RFC6991bis. (I guess we once called it revision-identifier
    because there was no clear understanding yet that we will have a
    revision-date and a revision-label.) Note that dropping the
    definition of revision-identifier from RFC6991bis and defining a
    revision-date type in ietf-yang-revisions also causes the
    dependency on ietf-yang-types to go away.
"""

The \d pattern allows numerals from other scripts than traditional latin/arabic numbers. Therefore the pattern should be updated to only allow [0-9]. Consider proposed changes to 6991'.

**Comment by xorrkaz** [comment]
Agreed.  I've already updated the YANG Semver module to use [0-9].
