### ISSUE TITLE
Clarify behavior of unaware compilers and tools

### ISSUE THREAD

**Issue by janlindblad** [netmod-wg/yang-ver-dt#169]
On March 6 Jürgen Schönwälder wrote on the subject "WG Last Call: draft-ietf-netmod-yang-module-versioning-05"

"""
* RFC 7950 compatibility

  An RFC 7950 compliant implementation will treat

    import example-module {
      rev:revision-or-derived 2.0.0;
    }

  as if    were

    import example-module;

  and hence it may import a revision that is not in the 2.0.0 branch.
  I believe this is a problem. An RFC 7950 implementation will also
  consider deprecate -> obsolete a legal BC change. I believe that
  changing the YANG RFC 7950 update rules fundamentally must be done
  in such a way that parsers not understanding the new rules fail
  instead of producing surprising results (e.g. by bumping the YANG
  version number.)

  Even if this document is implemented by a parser, the parser may get

    import example-module {
      rev:revision-or-derived omicron;
    }

  without knowing what the possible labels are and what the order
  relationship of them is. It seems that the revision-label-scheme
  statement has to be mandatory and a parser needs to stop if the
  announced revision-label-scheme is unknown to the parser.
"""

Consider if additional language is needed to explain why this is not a problem. Slide 13 @ https://datatracker.ietf.org/meeting/114/materials/slides-114-netmod-42-netmod-module-versioning-draft-update-01.pdf
may have some useful material.

**Comment by rgwilton** [comment]
I think that this issue is effectively resolved by the change in import-by-derived semantics to only be a recommendation rather than a change in import behaviour.

**Comment by rgwilton** [comment]
Mitigated by https://github.com/netmod-wg/yang-ver-dt/pull/183
