### ISSUE TITLE
What is the version component limit?

### ISSUE THREAD

**Issue by xorrkaz** [netmod-wg/yang-ver-dt#17]
Right now a version component is limited to int16.  Should this be increased to int64?

**Comment by BalazsLengyel** [comment]
In Ericsson I have never even seen a version of 100, but I don't object.

**Comment by rgwilton** [comment]
Current suggestion is to use the limit '0-999999' which can be checked with a relatively simple regex, fits into an int type, and is probably not unreasonable large.  (E.g. 1 release/second would still take 10+ years to wrap.)

**Comment by rgwilton** [comment]
The conclusion of the authors was to increase the version component to 2^31.

This has been updated in draft-ietf-netmod-yang-semver-01.
