### ISSUE TITLE
How does a consumer know which versioning scheme is being used?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#18]
Could use module tags, or a separate statement with an IANA registry.

**Comment by rgwilton** [comment]
An alternative choice would be to have different keywords for different version schemes.

**Comment by rgwilton** [comment]
Possible example discussed in the meeting:

label-scheme "semver"?

 import "foo-module" {
   revision-label-or-derived "1.0.0";
 }

revision "2019-04-01" {
   label "1.0.0";
   description "now using semver";
}

revision "2019-01-01" {
  description "previously published version";
}

**Comment by BalazsLengyel** [comment]
IMHO module tags are for categorizing YANG modules, not for describing what internal statements are used, so it would be a misuse.

Also making implementation of module-tags mandatory for supporting the versioning scheme is not nice.

IMHO 
- if we believe there will be a small number of versioning schemes used (1 or 2), we should use a separate statement.
semver 1.3.5m ;
- if we believe we will need to add new versioning schemes later on, we should prefix the version string with the used method e.g.
version "semver:1.4.5M" '

**Comment by Reshad-Rahman** [comment]
Agree that making module-tags mandatory isn't great. I think another option which was proposed is along the lines of:
version-scheme semver;
version 1.4.5M;

**Comment by BalazsLengyel** [comment]
IMHO it is better to include it in a single statement. The 2 bits belong together.

And using a single statement, if someone, god forbid, wants to include more then one versioning scheme, it would be possible.

**Comment by sunseawq** [comment]
How does a consumer know which revision date is being used? I feel the question is similar to the question you raised.

**Comment by rgwilton** [comment]
Agreed in DT meeting on 19/9.

For revision labels that conform to the YANG Semver format this can automatically be inferred by the format of the label.  For all other styles of revision-labels, I think that this is out of scope.

**Comment by jsterne** [comment]
Upon further discussion with the NETMOD WG, it has been decided to add another statement (extension) to declare what versioning scheme is being used. See issue #48.
