### ISSUE TITLE
Clarify that the top level nbc marker (or lack) is definitive

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#182]
In the per-node tags we explicitly describe that a bc-change-at tag can be used against a change that a tool might consider NBC by our rules (e.g. shrinking a range can be marked with bc-change-at).

But for the base Module Versioning draft we may not be clear than an author is allowed to explictly have the absence of the module level NBC tag even though there is a change in the module that a tool would analyze as NBC.

For example -> if a new revision of module has a range that has been reduced, but the author (aka server implementor) knows that the newly excluded values were never actually accepted by the server (i.e. were systematically rejected at edit time, validation time, or commit time), then they author is allowed to *not* flag the revision with the rev:non-backwards-compatible-revision tag.

**Comment by jsterne** [comment]
Need to soften this paragraph in 3.2 (to say something like "unless it is known that it is really no impact for all implementations/users"):  e.g. an implementation never accepted a commit of that value

   If a revision of a YANG module contains changes, relative to the
   preceding revision in the revision history, that do not conform to
   the module update rules defined in Section 3.1.1, then a "rev:non-
   backwards-compatible-revision" extension statement MUST be added as a
   substatement to the "revision" statement.

Also fix the similar statement in the YANG module.

**Comment by Reshad-Rahman** [comment]
Closing as per 2023-01-10 meeting minutes:
YANG Versioning Weekly Call Minutes - 2023-01-10
 
We have reached rough consensus on Issue #182 / PR #189:
- The top level NBC marker is a "MUST" if any rules are broken (even if a vendor knows the change is BC for their server)
- Reshad will take a final look at text and close the issue/Precedence
