### ISSUE TITLE
Can "revision-label" be used in include?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#20]
Can a revision-label be used instead of a revision-date in "include" or "import specific revision"?

Or do we just defer this to a new version of YANG (e.g. track as part of YANG.Next)? [My preference]

Or do we define separate extension statements [I'm not keen on this]

**Comment by BalazsLengyel** [comment]
As I remember  we sad that include/belongs-to is a much more
      strict relationship then import. For this  reason a strict
      date-based include should be enough.
      Who needs more work anyway ? :-)
    
    regards Balazs
    
    On 2019. 06. 10. 15:15, Robert Wilton
      wrote:
    
    
      
      Can a revision-label be used instead of a revision-date in
        "include" or "import specific revision"?
      Or do we just defer this to a new version of YANG (e.g. track
        as part of YANG.Next)? [My preference]
      Or do we define separate extension statements [I'm not keen on
        this]
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/netmod-wg/yang-ver-dt/issues/20?email_source=notifications\u0026email_token=ACFRA6HRNYBRVQ5VWRAKMALPZZHYVA5CNFSM4HWTNICKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYSAPFQ",
"url": "https://github.com/netmod-wg/yang-ver-dt/issues/20?email_source=notifications\u0026email_token=ACFRA6HRNYBRVQ5VWRAKMALPZZHYVA5CNFSM4HWTNICKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYSAPFQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Balazs Lengyel                       Ericsson Hungary Ltd.
Senior Specialist
Mobile: +36-70-330-7909              email: Balazs.Lengyel@ericsson.com

**Comment by sunseawq** [comment]
I agree with Balazs, suggest 
1.not include revision label in the submodule level and inherit revision label from the versioned main module if the main module included revision label.
2. not have revision label in the include statement.
The reason is when a module have multiple submodule and revision label of each submodule is different, it is hard to decide revision-label for the versioned main module. if each submodule have the same revision label, why not simply inherit revison label for the versioned main module

**Comment by rgwilton** [comment]
Agreed that this can be done in a future version of YANG, but not now.
