### ISSUE TITLE
What is the document relationship between the Revision Handling and Semver Docs?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#212]
Is the revision handling doc a base doc, that the Semver doc builds on?
Or are they both peer documents that have normative references to each other?
Or does the revision handling doc have an informative reference to Semver, with Semver having a normative reference to module revision handling?

**Comment by rgwilton** [comment]
We should aim for module versioning to only have an informative reference to Semver.  Semver will retain its normative reference back to module-versioning.

**Comment by Reshad-Rahman** [comment]
> We should aim for module versioning to only have an informative reference to Semver. Semver will retain its normative reference back to module-versioning.

They will go in as a pair I assume? I don't understand the aim of doing this.

**Comment by rgwilton** [comment]
@Reshad-Rahman, I guess that the thinking is that the module-versioning draft should be able to stand alone, in needs be, with the Semver being optional to implement.

**Comment by Reshad-Rahman** [comment]
@rgwilton now that I've caught up on some of the stuff which was discussed last November (when I was on PTO), I agree with module-versioning only having an informative reference to yang-semver.
