### ISSUE TITLE
Should "recommended-min-date" use history or date to check validity?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#213]
When we were using labels to decide if an import was valid, we were looking through the history.  But given that we are splitting the extension statements and only standardizing a single versioning scheme we could choose a different solutions here.  I.e.,

1.  For "recommended-min-date" it doesn't need to look at the history at all, and only does a date comparison to decide whether a given module satisfies the import.  The assumption/requirement here, is that this statement should only be used for linear revision histories.

2. For "recommended-min-ver", in the Semver doc, we could allow the import to understand the meaning/semantics of the Semver version label, i.e., allow any version that either (with some wildcard indications).  E.g.,:
   1. has the same major & minor numbers and same or later patch number
   2. has the same major and later minor version, patch ignored.
   3. has a later major number, minor and patch numbers ignored.

Making these changes, would, I think that we could delete the text about walk back through the revision history, and may allow the text about preserving revision history to be simplified to just managing/preserving the nbc-change marker.

**Comment by rgwilton** [comment]
Change to check against date only.  Retain text on changing history (except for bit about import min-revision).

**Comment by rgwilton** [comment]
POR to strip labels in modules (assuming that makes sense).

**Comment by rgwilton** [comment]
Rob to send diff that he started with + proposed names.

**Comment by Reshad-Rahman** [comment]
> Rob to send diff that he started with + proposed names.

@rgwilton I am starting to look at this now. If you have diffs please send them.

**Comment by Reshad-Rahman** [comment]
> When we were using labels to decide if an import was valid, we were looking through the history. But given that we are splitting the extension statements and only standardizing a single versioning scheme we could choose a different solutions here. I.e.,
<snip>
> 2. For "recommended-min-ver", in the Semver doc, we could allow the import to understand the meaning/semantics of the Semver version label, i.e., allow any version that either (with some wildcard indications).  E.g.,:
>    
>    1. has the same major & minor numbers and same or later patch number
>    2. has the same major and later minor version, patch ignored.
>    3. has a later major number, minor and patch numbers ignored.
> 

@jclarke-csco FYI. But I don't recall if we agreed to do this change in semver.

**Comment by xorrkaz** [comment]
My recollection is that we agreed to keep it simple and not introduce wildcarding.  Essentially, we do a numerical comparison at each integral part of the version identifier.  That's how I've written the text in the proposed PR.

**Comment by rgwilton** [comment]
> My recollection is that we agreed to keep it simple and not introduce wildcarding. Essentially, we do a numerical comparison at each integral part of the version identifier. That's how I've written the text in the proposed PR.
Yes, my recollection was that for a revision X.Y.Z then we would match anything on X.Y with Z or later., X, with Y or later, or any version greater than X.  I.e., the wildcards are not required because they are implicit.
