### ISSUE TITLE
Should we change the name/prefix of the YANG library module in revision handling doc?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#215]
The scope of the augmentations has changed to just the conformance flags, and hence changing the name of the module probably makes sense.

Also, given that the two modules are really small, it might also be worth considering whether the updated module revision handling doc just has a single YANG module rather than two:
 - the only downside I can see of having a single module is that YANG library may be updated to pull in these flags directly in future (or we could even do that as a very simple YANG library bis).

**Comment by rgwilton** [comment]
ietf-yang-revisions =>
  ietf-yang-compatibility?
  ietf-yang-revision-compatibility
  perhaps just keep as is.

ietf-yang-library-revisions =>
  ietf-yang-library-status
  alternative - could do RFC 7895bis.

Maybe ask WG + authors whether to do a YANG library bis instead?

**Comment by Reshad-Rahman** [comment]
Revisiting this, I don't think this data belongs to yang-library's schema. So I don't think we should be augmenting yang library's module and instead have our own module, with just these 2 booleans. ietf-yang-compatibility is my preferred name right now.

   module: ietf-yang-library-revisions
     augment /yanglib:yang-library/yanglib:schema:
       +--ro deprecated-nodes-implemented?   boolean
       +--ro obsolete-nodes-absent?          boolean

**Comment by rgwilton** [comment]
ietf-yang-status-conformance

**Comment by xorrkaz** [comment]
I have removed all "revision-label" mention from Semver.  Instead, I'm referring to the version leaf and the concept of a YANG artifact version.  The major changes are already in GitHub for review.

**Comment by Reshad-Rahman** [comment]
Discussed in Feb 13th meeting. We will be keeping the new module name but still augmenting YL (everyone except Reshad was in favour of augmenting YL).
