### ISSUE TITLE
Copy diagram from section 3.4 on mod revision handling to semver

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#219]
Consider whether we should include or copy the diagram to highlight how Semver labels match up or equate to revision dates.

**Comment by Reshad-Rahman** [comment]
Section 3.5?

**Comment by Reshad-Rahman** [comment]
> Section 3.5?

It was 3.5, now 3.4.

**Comment by Reshad-Rahman** [comment]
@xorrkaz assigning this to you, but I don't know if you've done this already.
