### ISSUE TITLE
NETCONF: do we need the ability to support version selection for schemas

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#22]
e.g. client could select vendor-xxx-native@2.0.0 AND ietf-routing@2.3.0

Otherwise we would need 1 schema version for each possible version combo of vendor-xxx-native@X, ietf-routing@Y and OpenConfig@Z?

=================================================================
Hi all,
 
Last week (email + meeting) there seemed to be consensus on the use of “root path” method for RESTCONF.
 
For NETCONF, we discussed using capabilities. Extending the capabilities to include “schema versions” seems sensible, with 1 top-level schema per schema family where family is e.g. vendor-xxx-native, ietf, OpenConfig.
An example of schema-versions advertised: vendor-xxx-native_1.2.1, vendor-xxx-native_2.0.0, ietf_2.3.0. We also need an RPC for the client to select which schema-version (among the ones advertised by the server) it wants to use.
If a client doesn’t call the SetVersion RPC, then the server’s behavior is to resort to default schema version (when multiple versions of schemas are supported).
If a server doesn’t advertise any schema-versions, client doesn’t call SetVersion RPC and both behave as they do today.
 
Thoughts on this?
 
Regards,
Reshad.

**Comment by rgwilton** [comment]
This issue is now solved via the use of custom schema, if they are supported.
