### ISSUE TITLE
Remove all instances of revision label in module-versioning

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#227]
- Abstract still mentioned revision label YANG extension
- Introduction says "This document defines a flexible versioning solution"
- Section 3 (Refinements to ...) also mentions label but maybe that stays
- Section 3.4 has to be (re)moved (there is another issue to copy it to yang-semver). Call it version identifier if it stays.
- Section 4.1 (recommended-min-date) still mentions revision label
- Section 4.1.1 redo but without labels (just min-date). Do this via #213 ?
- YANG module says "please replace label version with 1.0.0", remove that

**Comment by rgwilton** [comment]
Thinking about it some more, I thought that we were going to keep an informative reference for section 3.4, to better explain the example.  But another choice would be to just delete the text in 3.4, or move it to the Semver draft.

**Comment by Reshad-Rahman** [comment]
Feb 20th meeting: agreement to keep version identifier/label in module-versioning example (diagram and module) for illustrative example of branching.
