### ISSUE TITLE
Should we import "yang:revision-identifier" from RFC 6991bis?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#23]
ietf-yang-revisions.yang wants to use a typedef to identify a revision.

A type has been added to a recent bis version of RFC 6991.  Ideally, the ietf-yang-revisions.yang module would import the type, with a rev:revision-or-derived statement to specify the minimum import version.

However, it is not obvious whether it is a good idea for the module that defines the rev:revision-or-derived extension to also make use of that extension in the same module.  It seems quite circular.

Hence, it might be better if the ietf-yang-revision.yang module doesn't import the revision typedef, and instead just redefines it, avoiding the dependency?

**Comment by BalazsLengyel** [comment]
Hello,

IMHO avoid importing anything into ietf-yang-revisions.yang. Any imported module might itself be “revisioned” and start using e.g. the revision-label. That would lead to circular imports which are not allowed. Pyang gives “error: circular dependency for module” for circular imports.

Regards Balazs

**Comment by rgwilton** [comment]
When discussed on the alias, there was the recommendation from Juergen that we should try and reuse types where possible (because that gives the maximum information).  I think that a potential solution here is to put the dependency in body of the draft (when it introduces the YANG module).

**Comment by Reshad-Rahman** [comment]
Pick it up (based on what stage 6991bis is at) or redefine?

**Comment by jsterne** [comment]
From weekly meeting 2021-01-05: Use the new types from 6991bis but *don't* import by revision. Just say in comments/description that the 'bis' version is needed.  If 6991bis isn't ready when we go to publish, then just pull in the definition into this module.  Close this issue once the updates are in the versioning draft.

**Comment by Reshad-Rahman** [comment]
We are already using yang:revision-identifier from 6991-bis for revision-date-or-label

**Comment by Reshad-Rahman** [comment]
Updated in https://github.com/netmod-wg/yang-ver-dt/commit/f82f55706200b1188a0c64b45d664ca7a7958057
