### ISSUE TITLE
Allow in-band mechanism for schema-set selection.

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#24]
From https://github.com/rgwilton/ver-selection-draft/issues/1

Raised by Michael Darwish:

Hello,

I've been looking at the version selection draft and reading through the mail archive trying to see if there was any discussion surrounding the use of port numbers to select a schema-set.

The issue I have with this proposed solution is that our netconf server runs in an environment that makes it very difficult to expose arbitrary ports. It would be much simpler to have an in-band method for schema-set selection, so that we don't have to coordinate with the operations team every time we want to deploy a change to the data model.

I'm aware that this is still a draft and still in discussion, but I wanted to know if I was missing some part of the discussion or misinterpreting the draft as it stands.

Thanks

**Comment by rgwilton** [comment]
Schema-set selection is now done via NETCONF RPC and RESTCONF path, avoiding the need to open up separate port numbers.
