### ISSUE TITLE
No descendent statements to input/output can be reordered

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#47]
From Martin Bjorklund on draft-ietf-netmod-yang-module-versioning-00:

o  3.1.1

    o  In statements that have any data definition statements as
       substatements, those data definition substatements MAY be
       reordered, as long as they do not change the ordering or any "rpc"
       "input" substatements.

  I think this needs to capture that no descendant statements to
  "input" can be reordered.  Same for "output" (note, "input" and
  "output" in both "rpc" and "action").

**Comment by rgwilton** [comment]
In addition to questioning why input/output statements need to be in order, it is worth noting that it is possible for modules to augment RPC input/output statements, which can presumably be in any order.  Hence it would seem the RPC input/output ordering is non-deterministic anyway ...

**Comment by Reshad-Rahman** [comment]
Section 3.1.1 of https://www.ietf.org/id/draft-ietf-netmod-yang-module-versioning-01.txt has been updated
