### ISSUE TITLE
Revision label for submodules

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#49]
From Martin Bjorklund on draft-ietf-netmod-yang-module-versioning-00:

o  3.3

    Submodules MUST NOT use revision label schemes that could be confused
    with the including module's revision label scheme.

  Hmm, how do I ensure that this MUST NOT is handled correctly?  What
  exactly does "could be confused with" mean?

**Comment by Reshad-Rahman** [comment]
Good point. What was meant by that the label space for modules and sub-modules are orthogonal.  e.g. the sub-module and module both have the same label, it shouldn't be inferred that the 2 are related.
We'll change/clarify the text.

Regards,
Reshad.

**Comment by Reshad-Rahman** [comment]
YANG versioning meeting: do we need versioning on sub-modules? Or just use dates.

**Comment by jsterne** [comment]
My initial reaction is that we should not preclude the use of revision label with a submodule. Submodules have their own version today. The trick is to define (or explicitly say it is out of scope) whether a module version must change if any underlying submodule versions change. That gets difficult if you consider simply moving a leaf from one sub-module to another (without changing anything else about it - its context, etc).

**Comment by Reshad-Rahman** [comment]
https://mailarchive.ietf.org/arch/browse/netmod/?q=Revision%20labels%20for%20submodules

**Comment by Reshad-Rahman** [comment]
See section 3.3 of https://www.ietf.org/id/draft-ietf-netmod-yang-module-versioning-01.txt

   Submodules MAY use a revision label scheme.  When they use a revision
   label scheme, submodules MAY use a revision label scheme that is
   different from the one used in the including module.

   The revision label space of submodules is separate from the revision
   label space of the including module.  A change in one submodule MUST
   result in a new revision label of that submodule and the including
   module, but the actual values of the revision labels in the module
   and submodule could be completely different.  A change in one
   submodule does not result in a new revision label in another
   submodule.  A change in a module revision label does not necessarily
   mean a change to the revision label in all included submodules.
