### ISSUE TITLE
Should version statement be at top level or under revision statement

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#5]
There seems to be two choices to where the version statement is placed:

(1) At the top level of a module definition.  It probably also needs a previous-version statement to show the version history.

(2) The alternative is for the version statements to be placed under the revision statements.  The one downside to this approach is that it means that sub-modules can have version statements.  Possibly, we can just say that they are ignored.

**Comment by rgwilton** [comment]
Currently, I've updated the draft to reflect (2).

**Comment by Reshad-Rahman** [comment]
(2) sounds good. Then you could have the sem-ver history for a version (if all revisions have a version stmt). For sub-modules, we shouldn't just say version-stmt is ignored, it should not be allowed?

**Comment by rgwilton** [comment]
Using the revision label approach, the version naturally appears under the revision only.
