### ISSUE TITLE
Backporting and version update with YANG semver

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#55]
What happens in a branch when the changes are backported in such a way that the content will be the same as one on the trunk.
For example, if a change is added to 1.2.2M which somehow make that content the same as 2.0.0, would that be a 1.2.3M or 2.0.0?
 
           1.0.0                       
             |  \                      
             |   1.1.0 -> 1.1.1m -> 1.1.2M         
             |    |                          
             |   1.2.0 -> 1.2.1M -> 1.2.2M -> 2.0.0?
             |    |
             |   1.3.0 -> 1.3.1
             |
           2.0.0     
             |    \          
             |    2.1.0 -> 2.1.1M

![image](https://user-images.githubusercontent.com/5272591/78049919-a10cd100-7349-11ea-9c5b-67a5ce517e9d.png)

**Comment by jsterne** [comment]
If that change makes the child of 1.2.2M absolutely identical to 2.0.0 then just take 2.0.0.  I don't think we should allow the creation of another second 2.0.0 that has a different revision history.

So IMO it would become 1.2.3M (and 1.2.3M would just by coincidence happen to be the same, other than revision history, as 2.0.0).

Jason

**Comment by Reshad-Rahman** [comment]
YANG versioning meeting: this is corner case. It is ok to have 2 different version numbers with same schema content but different revision history. We can go from 1.2.2M to 1.2.3M or 2.0.0 but the 2 would have different revision history. Not sure if draft needs to be updated.

**Comment by jsterne** [comment]
Yes - I think that should be allowed. We can't preclude that versions on different branches end up with the same content (and they should have different revision labels and history).

**Comment by jsterne** [comment]
Should we put some text in module-versioning to address this?  It isn't specific to revision-label (also applies to version dates) so it should probably not go in section "3.3 Revision Label". Perhaps in section 3 we could add this:

It is acceptable that two versions of a module have the identical content except for the revision history. This could occur, for example, if a module has a branched history and identical changes are applied in multiple branches.

**Comment by Reshad-Rahman** [comment]
Yes text should be added to module-versioning. Proposed tweak to the text above:

It is acceptable that two versions of a module have identical content and revision-label except...

**Comment by Reshad-Rahman** [comment]
The text added conflicts with https://github.com/netmod-wg/yang-ver-dt/issues/58?

**Comment by jsterne** [comment]
No - I don't think that tweak is what I intended and it isn't the same case as #58. I'm talking about a case more like this (different revision labels, same module content):

- Start with 1.0.0
- add a new leaf called "foo" to 1.0.0 and now we have 1.1.0
- add a new leaf called "bar" to 1.1.0 and now we have 1.2.0
- add the "bar" leaf back to 1.0.0, call it 1.0.1_backwards_compatible
- remove the "foo" leaf from 1.2.0 and call it 1.2.1_non_backwards_compatible
- 1.0.1 and 1.2.1 are the same except for the revision history (including the current label, which I was considering as part of the revision history)

Illustrated (time flows left to right):
1.0.0 --- 1.1.0  --- 1.2.0 ---------------1.2.1_non_backwards_compatible
  \
    ------------------------- 1.0.1_backwards_compatible

**Comment by Reshad-Rahman** [comment]
OK this is different from the case initially discussed in this issue: the 2 module versions above end up with same content and revision-label  (2.0.0) but the history is different.
What I currently have in github is:
`Two versions of a module MAY have identical content and revision-label except for the revision history.`
I can change it to the following if we view current revision-label as part of the history:
`Two versions of a module MAY have identical content except for the revision history.`

When the revision-label is the same (but prior history different), this conflicts with https://github.com/netmod-wg/yang-ver-dt/issues/58, here's the text Balazs added:
`If two YANG modules contain the same module name and the same 
      revision-label in their latest revision statement, then the two modules 
      MUST be the same (except for possible white space at the end of each line.)`
In teh email I sent today I suggested changing this to:
`If two YANG modules contain the same module name and the same 
      revision-label in their latest revision statement, then the two modules 
      MUST be the same (except for the revision history and possible white space at the end of each line.)`
@BalazsLengyel thoughts?

**Comment by rgwilton** [comment]
As per the email.  I don't think that we should allow two files with the same version but different histories.

It is okay to publish a 1.2.3M with the same content as 2.0.0 (to keep the revision history on the 1.2.2 branch).  Or is it okay to not create 1.2.3M at all, and just change the schema version used by the device to 2.0.0.  But having two different versions of 2.0.0 with different histories should not be allowed.

**Comment by Reshad-Rahman** [comment]
Ack. I'll fix the test I commited yesterday

**Comment by Reshad-Rahman** [comment]
Last paragraph of section 3.3 of https://www.ietf.org/id/draft-ietf-netmod-yang-module-versioning-01.txt
