### ISSUE TITLE
versioning procedures (RFC vs. I-D)

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#56]
Hi,

I just want to confirm that all the proposed documentation procedures
using new extensions are limited in scope to published modules only,
and not applied to unpublished modules (terms defined in RFC 8407).

IMO it would be harmful to module usability to assign revision-labels or
include revision-related extensions in unpublished modules (e.g., Internet Drafts).
Consider how cluttered and confusing the client-server modules would be
if the 50+ NBC changes and versions were tracked through all the I-Ds.

For IETF modules, the first usage of the revision-label
should be in the initial RFC, and be set to 1.0.0.

If the RFC is ever republished then one can expect to find an updated
revision-label and possibly extensions tracking NBC changes.

Andy

**Comment by Reshad-Rahman** [comment]
From: Italo Busi <Italo.Busi@huawei.com>
Date: Thursday, April 2, 2020 at 5:06 AM
To: "Reshad Rahman (rrahman)" <rrahman@cisco.com>, 'Andy Bierman' <andy@yumaworks.com>, "Joe Clarke (jclarke)" <jclarke@cisco.com>
Cc: NetMod WG <netmod@ietf.org>
Subject: RE: [netmod] versioning procedures (RFC vs. I-D)
 
Reshad,
 
My doubt and, if I understand well also Andy’s question, is about the fact that before publishing an RFC-bis with e.g., 1.1.0, we will have a set of Internet-Drafts updating the RFC with 1.0.0
 
What versions should be used in the YANG modules published in these Internet-Drafts?
 
Think about the following scenario: -00 version provide BC changes to the RFC module but the -01 version provide NBC changes to what has been added in the -00 module (thus the -01 version is BC with the RFC 1.0.0 module but NBC with the -00 version module)
<RR> So bis 00 would be 1.1.0 (BC with RFC module).
Bis 01 should be updated according to its relationship to the RFC module (bis 00 doesn’t matter anymore), when RFC bis is published it won’t have the full history.
 
Hope I correctly understood your question.

**Comment by Reshad-Rahman** [comment]
> If the RFC is ever republished then one can expect to find an updated
> revision-label and possibly extensions tracking NBC changes.

The semver scheme allocates a major version of 0 for pre-releases where the BC/NBC rules do not apply.  I agree that a first official RFC release should be 1.0.0 (from a semver revision-label standpoint).  From a design team standpoint, I know we mentioned the 0 versioning early on, but I don’t think we spent much time talking about modules under development overall.

My take would align to yours that we wouldn’t clutter a module with development NBC tracking.

Joe

**Comment by Reshad-Rahman** [comment]
This semver plan is not very intuitive and not sure it works.
 
draft-00
 
   container the-container;             version 0.1.0      OK
 
draft-01:
   container my-container;             version 0.2.0;   rules violated; NBC should force 1.0.0
 
draft-02:
 
    container my-container {           version 0.3.0; should be 1.1.0 
        leaf my-leaf { type int32; }
    }            
 
RFC-1:
 
    container my-container {           version 1.0.0;  should be 2.0.0 according to NBC rules
        leaf my-leaf { type uint32; }
    }            
 
bis-draft-00:
 
   container my-container {           version 1.1.0; OK
        leaf my-leaf { type uint32; }
        leaf another-leaf { type int32; }
    }            
 
bis-draft-01:
 
  container my-container {                  diff against RFC-1:  version 1.1.0 but already used; use 1.2.0?
        leaf my-leaf { type uint32; }
        leaf another-leaf { type uint32; }
    }            
 
bis-draft-02:
 
  container example-my-container {                  diff against RFC-1:  version 2.0.0 but use 1.3.0 instead?
        leaf my-leaf { type uint32; }
        leaf another-leaf { type uint32; }
    }            
 
[repeat NBC step bis-draft-02 10 times.... now up to version 12.0.0 or is it 1.13.0? something else?
 
RFC-2:   publish draft-12 as RFC-2: now change the label from 1.13.0 to 2.0.0? or leave it 12.0.0?
 
IMO it is very confusing that the stated rules are so inconsistent and are violated so many ways.
There should be no revision-label at all in Internet Drafts because these documents are unpublished.
They should only be added to the RFC version.
 
The semver procedures are not intended to work for unpublished modules that are only
meant for review, not for implementation. The revision-label provides only noise in Internet Drafts.
<RR2> I think it’s useful to have a revision label in a draft because it indicates nature of changes (BC v/s NBC) compared to the previous published revision (RFC).
But you are absolutely right that setting the version based on changes with the previous draft revision is useless and confusing.
 
Regards,
Reshad.

**Comment by Reshad-Rahman** [comment]
https://mailarchive.ietf.org/arch/msg/netmod/drLg30T9vgKGtE7tIKjgleQXexQ/

**Comment by Reshad-Rahman** [comment]
Authors meeting on Apr 14th: no objections to proposal from Rob using paragraph 9 of https://semver.org/. See Apr 3rd email for proposal. Main requirement is seen as having unique version per (published) ID. 
We discussed using longer draft name (instead of 6991bis) but decided against it.

**Comment by Reshad-Rahman** [comment]
This is now being addressed in the semver draft. Should we take off the updated-rev-mod-handling tag?

**Comment by jsterne** [comment]
Should we put a note in updated-rev-mod-handling that any revision-label scheme SHOULD (or MUST?) describe how to deal with pre-release YANG modules and RFC YANG modules being updated?

**Comment by jsterne** [comment]
This was discussed on the weekly call. We felt it is not necessary and the yang-semver draft addresses it for that particular scheme.
