### ISSUE TITLE
Revision-label identifies a module version

### ISSUE THREAD

**Issue by BalazsLengyel** [netmod-wg/yang-ver-dt#58]
A specific revision-label identifies a specific version (variant) of the module. If two files contain YANG modules with the same module name and the same revision-label in their latest revision statement, then the two modules MUST be the same (except for possible white space at the end of each line.)

 This requirement should be stated in the draft.

**Comment by Reshad-Rahman** [comment]
Addressed by Balazs in https://github.com/netmod-wg/yang-ver-dt/commit/38beb5810c43a1886e55f07b48c15e457134493f?

**Comment by Reshad-Rahman** [comment]
Most people think that whitespace change should lead to editorial change.
But we all seem to agree that same schema and same revision-label+date means same revision history:
Last paragraph of section 3.3 of https://www.ietf.org/id/draft-ietf-netmod-yang-module-versioning-01.txt 

@BalazsLengyel, can we close this or do you wnat to keep it as open issue?

**Comment by Reshad-Rahman** [comment]
Closing this issue but keeping https://github.com/netmod-wg/yang-ver-dt/issues/8 open to track the question on whitespace changes
