### ISSUE TITLE
IANA considerations

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-ver-dt#59]
From Rob:
The module-versioning, and possibly semver, document are going to give new instructions to IANA. e.g. are we going to ask them to add rev:revision-label and nbc-change. These instructions will need to be in IANA section and we need to get early review from IANA to make sure they are happy with the instructions

**Comment by Reshad-Rahman** [comment]
Considering section 5.3 + Appendix A which are in semver document, I think instructions to IANA should go in that document. I don’t think IANA should be adding revision-label and nbc-change statements, that’s the authors job. Someone (YANG-Doctor, IANA?, RFC Editor?) will have to check that the these statements are correct.  So the instructions to YDs will have to be updated for sure.

**Comment by rgwilton** [comment]
Example  https://tools.ietf.org/html/rfc8294 section 5.1

**Comment by Reshad-Rahman** [comment]
Rob will send text to WG

**Comment by rgwilton** [comment]
Lada has raised an issue about the difference in meaning between deprecated and obsolete in the IANA definitions vs the YANG definitions.  We should try and address this.

His email comments are:

I don't know whether this has been discussed, but one issue that might need to be addressed is the difference between IANA and YANG in the definitions of "obsolete" and "deprecated" - the details are here (slide 5):

https://datatracker.ietf.org/meeting/104/materials/slides-104-dnsop-sessa-yang-types-for-dns-classes-and-resource-record-types-00

The best solution would be to unify the definitions. If this is not possible (in a short term), then it is IMO necessary to mark an entry that is made obsolete or deprecated in an IANA registry as "obsolete" in the YANG module.

**Comment by rgwilton** [comment]
We think that the IANA text is okay, but need to decide on whether to take action on Lada's comment?

**Comment by Reshad-Rahman** [comment]
We decided in the weekly meeting that while Lada's comment is valid, trying to align IANA and YANG terminology is outside our scope.
