### ISSUE TITLE
Is changing the ordering of nodes an NBC change?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#6]
RFC 6020 allows the ordering of nodes to be changed, RFC 7950 section 11 does not.  What is the right answer here?  RFC/action needs to be considered, as per https://tools.ietf.org/html/rfc7950#section-7.5.7

**Comment by rgwilton** [comment]
The current direction of the solution (e.g. the schema comparison draft) and the specification in the module revision draft, is that the ordering of data nodes should not matter, except for RFC parameters.  I propose that we take this position for the moment and close this issue.

**Comment by Reshad-Rahman** [comment]
> The current direction of the solution (e.g. the schema comparison draft) and the specification in the module revision draft, is that the ordering of data nodes should not matter, except for RFC parameters. I propose that we take this position for the moment and close this issue.

Rob, sounds good to me.

**Comment by jsterne** [comment]
Agree

**Comment by Reshad-Rahman** [comment]
June 30th meeting: allow reordering of nodes except where 7950 mandates order. e.g. input/output for actions/RPCs. Updating section 11 7950.

**Comment by Reshad-Rahman** [comment]
Addressed in https://tools.ietf.org/html/draft-ietf-netmod-yang-module-versioning-01#section-3.1.1
