### ISSUE TITLE
Can there be gaps in the semantic version history?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#61]
Are there allowed to be gaps in the version history in a YANG file?

E.g. is the history allowed to be as follows (skipping out revision/version 1.1.0):

{{{
         revision 2017-04-20 {
           description "Add new functionality, leaf 'baz'";
           rev:revision-label "1.2.0";
         }

         revision 2017-04-03 {
           description "First release version.";
           rev:revision-label "1.0.0";
         }
}}}

**Comment by xorrkaz** [comment]
I think this is allowed.  From a comparative standpoint it works within the semver rules.  And I see nothing in the semver spec that would disallow this.

**Comment by jsterne** [comment]
I don't think we should block an author from skipping a digit. If they want to go from 1.0.0 to 1.3.0 that's up to them. They may have had internal versions before releasing for example.

Or are you talking about actually removing a revision statement from the history? I think we settled on allowing that but it does mean you can't reconstruct the entire tree of revisions as easily.  We probably don't want to recommend removing revision statements that contain our NBC tag.

**Comment by rgwilton** [comment]
One issue with allowing gaps is that is could break "import revision-or-derived". 

E.g. say the versions were 1.0, 1.1, 1.3, and you wanted to import from version "1.2" or later, then version "1.3" would not be valid because it doesn't contain version "1.2" in the history.

Whether this would be an actual problem probably needs more discussion/thought.

**Comment by xorrkaz** [comment]
This has been resolved in recent updates to both yang-semver and yang-module-versioning.
