### ISSUE TITLE
Inclusion of deviations in packages issue

### ISSUE THREAD

**Issue by lana-wu** [netmod-wg/yang-ver-dt#62]
Jan raised a deviation issue:  Current YANG packages allow to contain deviations, but RFC 7950 restric the use of deviations

on the call of NETMOD YANG Version:
- Raise issue to track.
- Do we need restrictions on where these are allowed?
- Probably needed for vendors (e.g. to accurately describe devices)
- Probably need to restrict these in SDO modules?  But perhaps already covered by existing module rules anyway, and can perhaps refer back to that?

**Comment by BalazsLengyel** [comment]
The only restriction I found was: 
"... deviations MUST never be part of a  published standard ... "

Our current plans do not include any deviations only a place where vendors can register their deviations. IMO as long as we don't specify any packages where IETF specifies specific deviations we are OK.

Or did you think about something else ?

**Comment by jsterne** [comment]
Closed. Vendor packages can contain modules with deviations, but standards packages MUST not contain deviations.
