### ISSUE TITLE
Packages and Library are separately defined and somewhat different

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#67]
This issue was actually previously discussed and after a number of iterations and debates, we ended up with the current approach in https://tools.ietf.org/html/draft-ietf-netmod-yang-packages-00.  The main reasons:
- we want the instance data view of packages to match the view shown by a server
- reusing the library module sets was going to be too restrictive and likely cause proliferation of many small module sets

Previous discussions around this were tracked in the following issues from another older repo:
https://github.com/rgwilton/YANG-Packages-Draft/issues/10
https://github.com/rgwilton/YANG-Packages-Draft/issues/11
https://github.com/rgwilton/YANG-Packages-Draft/issues/12

**Comment by rgwilton** [comment]
Assigned to Jan.  Jan to investigate if he wants to reopen this.

**Comment by janlindblad** [comment]
We discussed an alternative way of grafting packages on top of YL. This was clearly doable, but did not lead to any significant advantages. At least we looked.
