### ISSUE TITLE
Do we assume that a module has an implicit semver if none as been specified?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#7]
Probably we don't want to do this, because there might be multiple revisions, and we don't want to assign them the same default semver.

However, we must ensure that we state how to order module revisions between those that have a semver and those that don't.

Do we need to make any accommodations for import statements, to allow them to pick up revisions without an assigned semver?  E.g. how do we handle imports against already modules in already published RFCs?

**Comment by Reshad-Rahman** [comment]
For modules in already published RFCs, doesn't import by revision work? If any of these modules come to use semver then these versions can then be imported by importing via semver?

**Comment by rgwilton** [comment]
Perhaps could allow import statement to have both import by verison and revision where it would accept either.

**Comment by rgwilton** [comment]
Another alternative could be define "semver:revision" that would be allowed to coexist with "semver:version" without breaking the YANG backwards compatibility rules.

**Comment by BalazsLengyel** [comment]
I always had doubts about this implicit semver, so I am happy if
      we remove it.
    regards Balazs
    
    On 2019. 06. 04. 15:57, Robert Wilton
      wrote:
    
    
      
      Given that the import is "revision-or-derived" and that the
        semantic version is just an optional label for a revision, then
        my expectation is that this is no longer required.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/netmod-wg/yang-ver-dt/issues/7?email_source=notifications\u0026email_token=ACFRA6HEGO7XYKQ2FLDBJVLPYZYDVA5CNFSM4G4LYJC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4UXLA#issuecomment-498682796",
"url": "https://github.com/netmod-wg/yang-ver-dt/issues/7?email_source=notifications\u0026email_token=ACFRA6HEGO7XYKQ2FLDBJVLPYZYDVA5CNFSM4G4LYJC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW4UXLA#issuecomment-498682796",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Balazs Lengyel                       Ericsson Hungary Ltd.
Senior Specialist
Mobile: +36-70-330-7909              email: Balazs.Lengyel@ericsson.com

**Comment by rgwilton** [comment]
Resolution: Close with no changes.  A revision label is just an alternative name for a revision, so an implicit semver is no longer required.
