### ISSUE TITLE
Where should guidelines text go?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#71]
Should the individual drafts update YANG author guidelines or should we try and do a bis update of YANG author guidelines?

What about YANG packages?  YANG package guidelines don't obviously fit into the scope of the YANG author guidelines for modules.  Possibly it would be better to have a separate section as part of the YANG packages document coving implementation guidelines and recommendations.

Also proposed that we focus on getting the guidelines text right first and then decide if the text needs to be reorganized later.

**Comment by jsterne** [comment]
We've been putting guidelines in the individual drafts.
