### ISSUE TITLE
Do we need a revision-or-derived-compatible extension (in addition to revision-or-derived) ?

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#75]
This issue came out of issue #11 but is somewhat independant of #11.

Import sub-statement extension “revision-or-derived” was introduced in module-versioning to alleviate the restrictions of import by date.  It reduces the set of importable revisions to those which are derived from a particular revision.

Consider module A (1.0.0) which imports module B using “2.0.0 or derived” and that there is no revision-label with MAJOR version > 2. This means A will be importing rev 2.Y.Z of module B.

If new revision 3.0.0 of module B is created (NBC changes), module A may end up importing 3.0.0 and this could break clients using module A. It’s also possible module A does not want the changes made in 3.0.0 of module B.

Should we also have another extension “revision-or-derived-compatible” to limit the import set to BC revisions? e.g “2.0.0 or derived compatible” would limit the imported version to 2.Y.Z, 3.0.0 would NOT be a candidate. Note that this would be done by looking at the revision history: revisions after 2.0.0 which are marked NBC via the rev:nbc-changes extension would be excluded.

**Comment by Reshad-Rahman** [comment]
Notes from Dec 14th 2020 virtual interim:

Thanks everyone for the feedback and comments on the mailing list and during the interim.
 
For the issue of revision-or-derived-compatible, there seems to be consensus that “revision-or-derived” is useful but compatibility constraints on imported modules  is better defined outside of the modules. So we will close https://github.com/netmod-wg/yang-ver-dt/issues/75, and open a new issue to look at how to define these constraints as meta-data elsewhere (e.g. in packages)
