### ISSUE TITLE
Are whitespace changes allow between two module instances with the same version (or revision)?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#8]
For example, if I reformat the module from 69 characters to 120 characters then is that an editorial change? Noting that the whitespace within a description statement has changed.

What if I keep description statements exactly the same and only change insignificant whitespace, .e.g. perhaps changing 4 char indentation to 2 char indentation?

**Comment by BalazsLengyel** [comment]
Such whitespace changes are the most frequently (andincorrectly, annoyingly) found changes to our modules. 
IMHO if you only change whitespace (excluding whitespace in singe or double quotes for description, reference, string default values etc.) that should be considered either
- no-change - preferrred
- editorial

**Comment by rgwilton** [comment]
Currently the checksum in the YANG packages draft will take into account whitespace.  This doesn't directly affect the version of a module, but should at least be considered.

**Comment by Reshad-Rahman** [comment]
PATCH update for whitespace change

**Comment by Reshad-Rahman** [comment]
Draft currently says editorial change.

**Comment by Reshad-Rahman** [comment]
Text from latest rev to be sent to WG.

**Comment by rgwilton** [comment]
Either in Reshad's dev branch, but not pushed.

**Comment by Reshad-Rahman** [comment]
Update has been pushed
