### ISSUE TITLE
Consider whether BC/NBC terminology should change to better align with Semver 2.0.0?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#80]
From a comment by @jwdonahue in #78:
 
The terminology around YANG versioning is unfortunate. NBC? **N**on-**B**reaking-**C**hange or **N**on-**B**ackwards-**C**ompatible? The SemVer terminology is **Breaking Change** and **Non-Breaking Change** or **Backwards Compatible Change**. I'll simply use Breaking Change and Compatible Change here.

We should consider whether we attempt to change terminology, and at least we should consider whether to spell out the "rev:nbc-changes" marker into something more explicit, perhaps "rev:non-compatible-changes".

**Comment by jsterne** [comment]
NBC may be ambiguous and we may be better expanding it out.

I'm not as certain about the "breaking" terminology though.

When I look at the Semver specs at semver.org the main page uses terms like:
- a backwards compatible manner
- backwards compatible API
- backwards incompatible API   <- we didn't love this term and preferred "non"
- backwards compatible functionality
- backwards incompatible changes

The word "breaking" is only in a single place on that page.

**Comment by jwdonahue** [comment]
That's a fair point, but if you [search the issues for the word compatible](https://github.com/semver/semver/issues?q=is%3Aissue+backwards), you'll get 116 hits. If you [search for breaking](https://github.com/semver/semver/issues?q=is%3Aissue+breaking) you'll get 129 hits.  A high number of those hits include [both words](https://github.com/semver/semver/issues?q=is%3Aissue+compatible+breaking) (75).

And then there's stackoverlow:

https://stackoverflow.com/search?q=%5Bsemver%5Dbreaking 148  
https://stackoverflow.com/search?q=%5Bsemver%5Dcompatible 106

What does ["backwards compatible"](https://www.google.com/search?q=What+does+backwards+compatible+mean%3F) mean?
What does ["breaking change"](https://www.google.com/search?q=What+does+breaking+change+mean%3F) mean?

I suppose it's a wash either way. Whatever you use, it's best to avoid acronyms wherever possible, it should defined, or a reference provided to something that does.

**Comment by rgwilton** [comment]
> 
> I suppose it's a wash either way. Whatever you use, it's best to avoid acronyms wherever possible, it should be defined, or a reference provided to something that does.

The RFCs will definitely define the terms and the meanings with the documents.

Formally the term is defined in https://datatracker.ietf.org/doc/draft-ietf-netmod-yang-module-versioning/

`Section 2:
   o  Backwards-compatible (BC) change: A backwards-compatible change
      between two YANG module revisions, as defined in Section 3.1.1

   o  Non-backwards-compatible (NBC) change: A non-backwards-compatible
      change between two YANG module revisions, as defined in
      Section 3.1.3
`
Sections 3.1.1 - 3.1.3 formally define the rules, which also reference back to the module update rules in RFC 7950.

However, it looks like we need to tweak the definition to also point to 3.1.2 as well in the definition of backwards compatible.

**Comment by rgwilton** [comment]
We renamed the extension (to make it more clear).

Action given to Reshad to update the draft and close the github issue.

**Comment by Reshad-Rahman** [comment]
nbc-changes has been renamed to non-backwards-compatible-changes in https://github.com/netmod-wg/yang-ver-dt/commit/2e347b9463947c1b7071e51502b08cae7c0f75e1

**Comment by Reshad-Rahman** [comment]
As Jason reminded me, it's actually supposed to be non-backwards-compatible (without -changes).

**Comment by Reshad-Rahman** [comment]
Fixed in 3a80723307d39be57d615b4c914c88b42b0e6f78
