### ISSUE TITLE
Remove checksums in YANG packages?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#82]
It is unclear whether it is too early for checksums in YANG packages, i.e. do they need further thought/work and hence should be removed for the moment.

One issue was regards to calculating the checksum given constraints about the impact of whitespace for versioning, but that issue seems to have been resolved.

The last discussion was that we should remove them from YANG Packages.  But perhaps we still want to double check that is the right next step before we take them out?

Either way, an issue tracking the change is helpful.

**Comment by jsterne** [comment]
In our Dec 15 weekly versioning call, we decided to move integrity and veracity of packages and modules outside the scope of all this work.  So I'm not sure we need/want to address this (at least not in initial RFCs).  Packages will still solve a lot of other problems and integrity/veracity is a side issue IMO.

**Comment by rgwilton** [comment]
Bo to remove the checksum text.  (The checksums in the examples will also need to be removed).

**Comment by lana-wu** [comment]
The checksum text has been removed in revision 02: https://datatracker.ietf.org/doc/html/draft-ietf-netmod-yang-packages-02
