### ISSUE TITLE
3.3 #3 confuses me.

### ISSUE THREAD

**Issue by jwdonahue** [netmod-wg/yang-ver-dt#84]
It reads:

```
    3.  If an artifact is being updated in an editorial way, then the
       next version number depends on the format of the current version
       number:

       i    "X.Y.Z" - the artifact version MUST be updated to "X.Y.Z+1"

       ii   "X.Y.Z_compatible" - the artifact version MUST be updated to
            "X.Y.Z+1_compatible".

       iii  "X.Y.Z_non_compatible" - the artifact version MUST be
            updated to "X.Y.Z+1_non_compatible".

```

If I've read correctly up to this point, the `_non_compat` postfix, indicates that version is not compatible with the previous version. What I don't understand is, if I only make editorial (non-breaking) changes to `X.Y.Z_non_compat`, then X.Y.Z+1 is in fact compatible with that earlier version, why must I propogate the `_non_compat` postfix?

Is it the case that once a breaking change is introduced into the lineage, all future changes must also be consider breaking?

Is it the case that an entire lineage must either be old style version or  SemVer style versions? I thought I read somewhere that, that wasn't the case.

Recall that I mentioned in another post that the version of the SemVer version string in use, is ambiguous? I am probably missing something, but I think this is where a new tag could come in handy. In the absence of the tag, always assume old style versions, otherwise use the [version meta tag](https://versionmeta.org) to know what you are working with, and apply the appropriate rules.  Since the tooling for VersionMeta is non-existent at this time, you could simply require the {Yang-SemVer} tag. I'd be happy to post a [VersionSchema](https://versionschema.org/) document for that purpose. I do already have one for [{SemVer}](https://github.com/VersionSchema/VersionSchema/blob/master/Schemas/SemVer.2.0.0.xml).

**Comment by rgwilton** [comment]
> 
> If I've read correctly up to this point, the `_non_compat` postfix, indicates that version is not compatible with the previous version. 

Correct.

>What I don't understand is, if I only make editorial (non-breaking) changes to `X.Y.Z_non_compat`, then X.Y.Z+1 is in fact compatible with that earlier version, why must I propogate the `_non_compat` postfix?

So, that a client that upgrades from an older version (e.g. say X.0.0) to X.Y.Z+1_non_compatible knows that it is a non-backwards-compatible upgrade.  If you removed the _non_compatible marker for X.Y.Z+1 then it would look like it is backwards compatible change when it is not.

Note that the module revision history will also indicate where non-compatible revisions have occurred with a separate marker.  I.e. the "rev:nbc-changes" statement described in https://datatracker.ietf.org/doc/draft-ietf-netmod-yang-module-versioning/

E.g., you would see something like:

`         revision 2017-12-31 {
           description "Added some new backwards compatible functionality here.'";
           rev:revision-label "1.3.2_non_compatible";
         }

         revision 2017-10-30 {
           description "Made some breaking change to the module definition";
           rev:revision-label "1.3.1_non_compatible";
           rev:nbc-changes;
         }

         revision 2017-08-30 {
           description "Clarified description of 'foo-64' leaf";
           rev:revision-label "1.3.1";
         }`

Obviously, they could have used versions 1.3.1, 2.0.0, 2.1.0 instead.  But that doesn't work for us in the case that 2.0.0 has already been released.  We need some more flexibility to be able to fix/improve older versions of the software in non-backwards-compatible ways, without forcing everyone to move to the latest version of the module (which would likely have very wide impact).

> 
> Is it the case that once a breaking change is introduced into the lineage, all future changes must also be consider breaking?

Yes, exactly, once you have poisoned a particular patch "branch" then it stays poisoned for all future changes on that patch branch (X.Y.*).  The aim here is allow for some limited branching for fixing issues, but still try and encourage the API to be upgraded in a regular Semver 2.0.0 way.

But you would be allowed to go from 1.3.2_non_compatible to some other major version number (e.g. 3.0.0).  But mostly once you end up making changes on these patch branches then you can regard them as dead-end twigs.  E.g., it is quite likely that a change that goes into 1.3.2_non_compatible would also be double committed to main head of the development tree.

> 
> Is it the case that an entire lineage must either be old style version or SemVer style versions? I thought I read somewhere that, that wasn't the case.

No, the intention is that you can entirely mix and match.  Obviously, you lose some visibility from a poisoned patch branch as to whether you can upgrade to a later revision in a backwards compatible way.  But that seems to be a reasonable trade off.  We are trying to add the minimum amount of complexity needed to meet the requirements.


> 
> Recall that I mentioned in another post that the version of the SemVer version string in use, is ambiguous? I am probably missing something, but I think this is where a new tag could come in handy. In the absence of the tag, always assume old style versions, otherwise use the [version meta tag](https://versionmeta.org) to know what you are working with, and apply the appropriate rules. Since the tooling for VersionMeta is non-existent at this time, you could simply require the {Yang-SemVer} tag. I'd be happy to post a [VersionSchema](https://versionschema.org/) document for that purpose. I do already have one for [{SemVer}](https://github.com/VersionSchema/VersionSchema/blob/master/Schemas/SemVer.2.0.0.xml).

As per my previous response, I think that this is handled by the rev:revision-label-scheme "yangver:yang-semver" annotation in the YANG module.  I.e. it ties the version string to the specification in https://datatracker.ietf.org/doc/draft-ietf-netmod-yang-semver.

**Comment by jsterne** [comment]
Might be worthwhile to expand the 3rd paragraph of section 3.2 (version -03) to briefly explain the motivation of the _COMPAT.

**Comment by jsterne** [comment]
Proposal for updates in:  https://github.com/netmod-wg/yang-ver-dt/pull/119

**Comment by jsterne** [comment]
PR was pulled into v06 of the draft.
