### ISSUE TITLE
The solution does not strictly extend semver 2.0.0

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#9]
The draft states that we support semver 2.0.0, but that is not completely true.

Semver.org 2.0.0 allows: "1.0.0-alpha", "1.0.0-alpha.1", "1.0.0-0.3.7", "1.0.0-x.7.z.92".
It also allows: "1.0.0-alpha+001, 1.0.0+20130313144700", "1.0.0-beta+exp.sha.5114f85".

I don't think that we want to allow either of these formats so I think that the draft must either list the parts of semver that it does not conform to, or perhaps just state which parts of semver 2.0.0 are allowed/supported.

**Comment by rgwilton** [comment]
Another key difference between the two approaches is that it seems that semver 2.0.0, always expects updates to happen to the latest revision.  E.g. it does not expect a chronological version history that goes 1.0.0 -> 2.0.0 -> 1.1.0.  Instead, it only really intends to support 1.0.0 -> 2.0.0 -> 2.1.0.

I somewhat question whether or not we should allow the sequence 1.0.0 -> 2.0.0 -> 1.1.0.  The alternative would be to require this to be versioned as 1.0.0 -> 2.0.0 -> 1.0.0m, hence retaining the strict linear semver version ordering.  But on the flip side, going from 1.1.0 to 2.0.0 is a major version change anyway, so it is not clear that the branched history is really a problem.

**Comment by BalazsLengyel** [comment]
For drafts in Ericsson we go from
1.0.0 to the next needed revision 1.0.1 or 1.1.0 or 2.0.0 immediately. Later during the review process, when many updates may be made, we only increase the patch level, so e.g. we might end up at 2.0.27 if we hav 27 unreleased updates.

**Comment by BalazsLengyel** [comment]
IMHO you should never see a YANG module (YAM) with 1.0.0 -> 2.0.0 -> 1.1.0
You will always base 1.1.0 on 1.0.0
So you end up with two separate YAMs
1.0.0 -> 2.0.0
and
1.0.0 -> 1.1.0
As these are 2 separate files, no problem

**Comment by BalazsLengyel** [comment]
About "1.0.0-alpha"
We should say that: anything after a - is accepted, but SHOULD be ignored as its significance is implementation specific..

**Comment by BalazsLengyel** [comment]
We should say that: 
      anything after a dash "-" is accepted, but SHOULD be ignored as
      its significance is implementation specific.
    Balazs
    
    On 2019. 03. 07. 18:10, Robert Wilton
      wrote:
    
    
      
      Another key difference between the two approaches is that it
        seems that semver 2.0.0, always expects updates to happen to the
        latest revision. E.g. it does not expect a chronological version
        history that goes 1.0.0 -> 2.0.0 -> 1.1.0. Instead, it
        only really intends to support 1.0.0 -> 2.0.0 -> 2.1.0.
      I somewhat question whether or not we should allow the sequence
        1.0.0 -> 2.0.0 -> 1.1.0. The alternative would be to
        require this to be versioned as 1.0.0 -> 2.0.0 -> 1.0.0m,
        hence retaining the strict linear semver version ordering. But
        on the flip side, going from 1.1.0 to 2.0.0 is a major version
        change anyway, so it is not clear that the branched history is
        really a problem.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/netmod-wg/yang-ver-dt","title":"netmod-wg/yang-ver-dt","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/netmod-wg/yang-ver-dt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rgwilton in #9: Another key difference between the two approaches is that it seems that semver 2.0.0, always expects updates to happen to the latest revision.  E.g. it does not expect a chronological version history that goes 1.0.0 -\u003e 2.0.0 -\u003e 1.1.0.  Instead, it only really intends to support 1.0.0 -\u003e 2.0.0 -\u003e 2.1.0.\r\n\r\nI somewhat question whether or not we should allow the sequence 1.0.0 -\u003e 2.0.0 -\u003e 1.1.0.  The alternative would be to require this to be versioned as 1.0.0 -\u003e 2.0.0 -\u003e 1.0.0m, hence retaining the strict linear semver version ordering.  But on the flip side, going from 1.1.0 to 2.0.0 is a major version change anyway, so it is not clear that the branched history is really a problem."}],"action":{"name":"View Issue","url":"https://github.com/netmod-wg/yang-ver-dt/issues/9#issuecomment-470611838"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/netmod-wg/yang-ver-dt/issues/9#issuecomment-470611838",
"url": "https://github.com/netmod-wg/yang-ver-dt/issues/9#issuecomment-470611838",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Balazs Lengyel                       Ericsson Hungary Ltd.
Senior Specialist
Mobile: +36-70-330-7909              email: Balazs.Lengyel@ericsson.com

**Comment by rgwilton** [comment]
My question could perhaps be restated as:
 - Can you publish a version 1.1.0 of a module after version 2.0.0 has been published?  (Both the 1.1.0 and 2.0.0 are based on 1.0.0, in separate files?
 - My interpretation of semver 2.0.0 rules is that generally isn't expected/allowed.  I.e. once 2.0.0 has been published, you cannot publish 1.1.0, and hence if both versions 1.1.0 and 2.0.0 exist then 2.0.0 MUST derive from 1.1.0, but possibly my interpretation is wrong.

**Comment by Reshad-Rahman** [comment]
- I believe the answer to the question in first bullet is yes. Version 10 of s/w has 1.0.0, Version 11 or 12 of s/w has 2.0.0 (major change made) and after that Version 10.1 of s/w has 1.1.0 because of a BC change.
- Second bullet, same understanding for me.

**Comment by rgwilton** [comment]
> * I believe the answer to the question in first bullet is yes. Version 10 of s/w has 1.0.0, Version 11 or 12 of s/w has 2.0.0 (major change made) and after that Version 10.1 of s/w has 1.1.0 because of a BC change.
> * Second bullet, same understanding for me.

The alternative solution here would be force  version 10.1 to go from 10.0.0 to 10.0.1m instead.

**Comment by BalazsLengyel** [comment]
Only about 2nd bullet. I see 2 files 
IMHO Semver does not say anything about the issue, so it is not prohibited. (Please point out the part of semver.org that prohibits this)

Yam1-verA contains 1.0.0 -> 1.1.0
Yam1-verB contains 1.0.0 -> 2.0.0

I may not even know whether 1.1.0 or 2.0.0 was created first. (Semver does not mandate a date parameter).
It would be strange if the adherence to semver would be dependent on an unknown date-time race between the two development teams.

**Comment by rgwilton** [comment]
I've raised an issue on the semver github issues tracker to query this: https://github.com/semver/semver/issues/504

**Comment by jsterne** [comment]
I've always thought that strict SemVer implies a simple single line of updates where every single update always happens at the head.  In strict SemVer you would not see 1.0.0 -> 2.0.0 -> 1.1.0.

But we agreed that updates to the non-latest-version (i.e. branching) is required in our solution.

So while I don't see a single direct line of 1.0.0 -> 2.0.0 -> 1.1.0, I *would* expect to see:
1.0.0 -> 2.0.0
and then some time later
1.0.0 -> 1.1.0

We should not require any m or M in that case.

**Comment by BalazsLengyel** [comment]
Also
1.0.0 -> 2.0.0
and
1.0.0 -> 1.1.0
will be in separate files

**Comment by jsterne** [comment]
Agree.
---------time--------->
1.0.0  ----------------------------> 1.1.0
   \
     \
       ----- >2.0.0

**Comment by jsterne** [comment]
agree
'-------------- time ----------->

1.0.0 -------------------------> 1.1.0
  \
    \ 
      -----> 2.0.0
'

**Comment by rgwilton** [comment]
> I've always thought that strict SemVer implies a simple single line of updates where every single update always happens at the head. In strict SemVer you would not see 1.0.0 -> 2.0.0 -> 1.1.0.

This is what I thought too.  But having raised this issue on the semver Github, everyone so far commented that releasing 1.1.0 after 2.0.0 is fine, expected, and required.

> 
> But we agreed that updates to the non-latest-version (i.e. branching) is required in our solution.
Agreed.

> 
> So while I don't see a single direct line of 1.0.0 -> 2.0.0 -> 1.1.0, I _would_ expect to see:
> 1.0.0 -> 2.0.0
> and then some time later
> 1.0.0 -> 1.1.0
> 
> We should not require any m or M in that case.
Yes, I am OK with this.  My aim here was to ensure that we are only extending the Semver 2.0.0 scheme and not breaking any of the current rules.  If Semver allows us to release 1.1.0 after 2.0.0 then that also works for me.

**Comment by sunseawq** [comment]
I am not sure releasing 1.1.0 after 2.0.0 is required, can you point me the link? In our implementation, we don't allow the sequence 1.0.0 -> 2.0.0 -> 1.1.0 and the first two numbers can be generated automatically based on whether NBC or BC.

**Comment by sunseawq** [comment]
> Only about 2nd bullet. I see 2 files
> IMHO Semver does not say anything about the issue, so it is not prohibited. (Please point out the part of semver.org that prohibits this)
> 
> Yam1-verA contains 1.0.0 -> 1.1.0
> Yam1-verB contains 1.0.0 -> 2.0.0
> 
Balazs, does  Yam1-verA and Yam1-verB stand for diffrent product type?

**Comment by rgwilton** [comment]
Now fixed to strictly extend Semver 2.0.0
