### ISSUE TITLE
Check that we are compatible with the pre-release guidance

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#91]
Forked from a comment from #78:

> 4. Tags in the current scheme, are either prerelease or build-meta tags, and the sorting rules for prerelease tags are non-semantic (Dev has higher precedents than Beta!). You could add something like an enumeration type tag where (Dev < Alpha < Beta < RC), or better yet, provide a means for developers to define their own. There's room here to cover something other than ASCII sort order, while preserving the SemVer style prerelease tag. Perhaps a quality tag allowing for a combination of flags for security reviewed, unit tested, human in the loop, etc.

Okay, this might be something that we need to consider further.

**Comment by rgwilton** [comment]
Probably a dup of #85.

**Comment by jsterne** [comment]
YANG Semver draft has guidance on pre-release versioning. It is compatible with Semver.
