### ISSUE TITLE
Mention submodules in YANG Semver draft

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#96]
Some places in the YANG semver draft explicitly describe how the rules work for submodules vs modules.

But in most of the text, the mention of module is also applicable to submodules.

Should we just put a disclaimer at the start that module = module + submodule ?  Or sprinkle "module or submodule" around the text in a bunch of places ?

**Comment by xorrkaz** [comment]
The semver draft refers to YANG "artifacts" to take into account packages.  I believe I define an artifact to mean module, submodule, or package.  Though, in the section that deals with modules specifically, I can ensure text on module+submodule.
