### ISSUE TITLE
unique revision-label and revision date in module history

### ISSUE THREAD

**Issue by jsterne** [netmod-wg/yang-ver-dt#98]
In our YANG versioning work we are proposing that a revision-label is unique and the revision history of a module must not contain the same revision-label twice.

We're debating whether we should state the same rule for revision *date* as well.

RFC7950 doesn't seem to explicitly say that revision date must not be duplicated in the revision history.

This issue came up recently in an OpenConfig discussion here:
Updates to OpenConfig types modules. · openconfig/public@f20ed84 (github.com)

Was it the intention of RFC7950 that a revision history should never have the same revision date twice ?

I think it is somewhat inferred from various drafts that describe how a module name + revision date uniquely identifies a module revision. But it doesn't seem to be explicitly stated in RFC7950.

If we disallow duplicate revision dates, that makes the module-name+date tuple unique, but it does mean that authors can't produce 2 versions of a module in the same day. In theory we *could* do something like this:
- require unique revision-labels
- allow duplicate revision dates

But in that case, only the module-name+revision-label can be the unique identifier for a revision.

**Comment by rgwilton** [comment]
Agreement was to not change the text from what we have today, and not to clarify the uniqueness of revision dates beyond what is already in RFC 7950.
